---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grid-and-cloud-database
spec:
  selector:
    matchLabels:
      role: grid-and-cloud-database
      environment: test
  serviceName: "grid-and-cloud-database-svc"
  replicas: 1
  template:
    metadata:
      labels:
        role: grid-and-cloud-database
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: grid-and-cloud-database
          image: fallen2320/grid-and-cloud-second-task-database:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "UTC"
            - name: PGTZ
              value: "Europe/Moscow"
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-localvolume
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 2000Mi
              cpu: 500m
      volumes:
        - name: database-localvolume
          hostPath:
            path: /var/database-grid-and-cloud-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: grid-and-cloud-database-svc
spec:
  type: NodePort
  ports:
    - name: p5432
      port: 5432
      targetPort: 5432
      nodePort: 32228
      protocol: TCP
  selector:
    role: grid-and-cloud-database