---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
      "BACKEND_API": "http://localhost:8080"
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid-and-cloud-frontend
  labels:
    app: grid-and-cloud-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grid-and-cloud-frontend
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grid-and-cloud-frontend
        tier: app
    spec:
      containers:
        - image: fallen2320/grid-and-cloud-second-task-frontend:latest
          imagePullPolicy: Always
          name: app
          env:
            - name: TZ
              value: "Europe/Moscow"
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /home/app/src/config.json
              subPath: config.json
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 1500Mi
              cpu: 500m
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: grid-and-cloud-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - name: p3000
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grid-and-cloud-frontend
